-- +goose Up
CREATE TABLE IF NOT EXISTS templates (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    creator_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    rules JSONB NOT NULL DEFAULT '[]'::jsonb,
    component_pool JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS components (
    id VARCHAR(255) PRIMARY KEY,
    template_id VARCHAR(255) NOT NULL REFERENCES templates(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    effects JSONB NOT NULL DEFAULT '[]'::jsonb,
    has_levels BOOLEAN NOT NULL DEFAULT FALSE,
    level_scaling VARCHAR(32) CHECK (level_scaling IN ('formula', 'tiers')),
    level_rule JSONB,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS builds (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    creator_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_id VARCHAR(255) NOT NULL REFERENCES templates(id) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    vote_score INTEGER NOT NULL DEFAULT 0,
    components JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS build_votes (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    build_id VARCHAR(255) NOT NULL REFERENCES builds(id) ON DELETE CASCADE,
    value SMALLINT NOT NULL CHECK (value IN (-1, 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, build_id)
);

-- +goose Down
DROP TABLE IF EXISTS build_votes;
DROP TABLE IF EXISTS builds;
DROP TABLE IF EXISTS components;
DROP TABLE IF EXISTS templates;