// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    id,
    name,
    description,
    creator_user_id,
    template_id,
    created_at,
    updated_at,
    tags,
    vote_score,
    components,
    is_private
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
`

type CreateBuildParams struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

type CreateBuildRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (CreateBuildRow, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatorUserID,
		arg.TemplateID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Tags,
		arg.VoteScore,
		arg.Components,
		arg.IsPrivate,
	)
	var i CreateBuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (
    template_id,
    scoped_number,
    name,
    description,
    category,
    effects,
    has_levels,
    level_scaling,
    level_rule,
    tiers,
    is_deleted,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, template_id, scoped_number, name, description, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
`

type CreateComponentParams struct {
	TemplateID   string
	ScopedNumber int32
	Name         string
	Description  pgtype.Text
	Category     string
	Effects      []byte
	HasLevels    bool
	LevelScaling pgtype.Text
	LevelRule    []byte
	Tiers        []byte
	IsDeleted    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.TemplateID,
		arg.ScopedNumber,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Effects,
		arg.HasLevels,
		arg.LevelScaling,
		arg.LevelRule,
		arg.Tiers,
		arg.IsDeleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    id,
    name,
    description,
    creator_user_id,
    stats,
    rules,
    components,
    is_private,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, description, creator_user_id, stats, rules, components, is_private, created_at, updated_at
`

type CreateTemplateParams struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	Stats         []byte
	Rules         []byte
	Components    []byte
	IsPrivate     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatorUserID,
		arg.Stats,
		arg.Rules,
		arg.Components,
		arg.IsPrivate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.Components,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, username, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBuild = `-- name: DeleteBuild :exec
DELETE FROM builds
WHERE id = $1
`

func (q *Queries) DeleteBuild(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBuild, id)
	return err
}

const deleteBuildSlotsByBuild = `-- name: DeleteBuildSlotsByBuild :exec
DELETE FROM build_slots
WHERE build_id = $1
`

func (q *Queries) DeleteBuildSlotsByBuild(ctx context.Context, buildID string) error {
	_, err := q.db.Exec(ctx, deleteBuildSlotsByBuild, buildID)
	return err
}

const deleteBuildVote = `-- name: DeleteBuildVote :exec
DELETE FROM build_votes
WHERE user_id = $1 AND build_id = $2
`

type DeleteBuildVoteParams struct {
	UserID  int32
	BuildID string
}

func (q *Queries) DeleteBuildVote(ctx context.Context, arg DeleteBuildVoteParams) error {
	_, err := q.db.Exec(ctx, deleteBuildVote, arg.UserID, arg.BuildID)
	return err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components
WHERE id = $1 AND template_id = $2
`

type DeleteComponentParams struct {
	ID         int64
	TemplateID string
}

func (q *Queries) DeleteComponent(ctx context.Context, arg DeleteComponentParams) error {
	_, err := q.db.Exec(ctx, deleteComponent, arg.ID, arg.TemplateID)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates
WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserByEmail, email)
	return err
}

const getBuildByID = `-- name: GetBuildByID :one
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE id = $1 AND is_private = FALSE
LIMIT 1
`

type GetBuildByIDRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) GetBuildByID(ctx context.Context, id string) (GetBuildByIDRow, error) {
	row := q.db.QueryRow(ctx, getBuildByID, id)
	var i GetBuildByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const getBuildVote = `-- name: GetBuildVote :one
SELECT user_id, build_id, value, created_at
FROM build_votes
WHERE user_id = $1 AND build_id = $2
LIMIT 1
`

type GetBuildVoteParams struct {
	UserID  int32
	BuildID string
}

func (q *Queries) GetBuildVote(ctx context.Context, arg GetBuildVoteParams) (BuildVote, error) {
	row := q.db.QueryRow(ctx, getBuildVote, arg.UserID, arg.BuildID)
	var i BuildVote
	err := row.Scan(
		&i.UserID,
		&i.BuildID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, template_id, scoped_number, name, description, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
FROM components
WHERE id = $1 AND template_id = $2
LIMIT 1
`

type GetComponentByIDParams struct {
	ID         int64
	TemplateID string
}

func (q *Queries) GetComponentByID(ctx context.Context, arg GetComponentByIDParams) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByID, arg.ID, arg.TemplateID)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, description, creator_user_id, stats, rules, components, is_private, created_at, updated_at
FROM templates
WHERE id = $1 AND is_private = FALSE
LIMIT 1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.Components,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, email, created_at, updated_at
FROM users
WHERE id = ANY($1::int[])
ORDER BY created_at DESC
`

type GetUsersByIDsRow struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []int32) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildSlotsByBuild = `-- name: ListBuildSlotsByBuild :many
SELECT build_id, category, position, component_id, level, tier
FROM build_slots
WHERE build_id = $1
ORDER BY category, position
`

func (q *Queries) ListBuildSlotsByBuild(ctx context.Context, buildID string) ([]BuildSlot, error) {
	rows, err := q.db.Query(ctx, listBuildSlotsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildSlot
	for rows.Next() {
		var i BuildSlot
		if err := rows.Scan(
			&i.BuildID,
			&i.Category,
			&i.Position,
			&i.ComponentID,
			&i.Level,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsByTemplate = `-- name: ListBuildsByTemplate :many
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE template_id = $1 AND is_private = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBuildsByTemplateParams struct {
	TemplateID string
	Limit      int32
	Offset     int32
}

type ListBuildsByTemplateRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListBuildsByTemplate(ctx context.Context, arg ListBuildsByTemplateParams) ([]ListBuildsByTemplateRow, error) {
	rows, err := q.db.Query(ctx, listBuildsByTemplate, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildsByTemplateRow
	for rows.Next() {
		var i ListBuildsByTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsByUser = `-- name: ListBuildsByUser :many
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE creator_user_id = $1 AND is_private = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBuildsByUserParams struct {
	CreatorUserID int32
	Limit         int32
	Offset        int32
}

type ListBuildsByUserRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListBuildsByUser(ctx context.Context, arg ListBuildsByUserParams) ([]ListBuildsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBuildsByUser, arg.CreatorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildsByUserRow
	for rows.Next() {
		var i ListBuildsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByTemplate = `-- name: ListComponentsByTemplate :many
SELECT id, template_id, scoped_number, name, description, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
FROM components
WHERE template_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListComponentsByTemplateParams struct {
	TemplateID string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListComponentsByTemplate(ctx context.Context, arg ListComponentsByTemplateParams) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponentsByTemplate, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ScopedNumber,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Effects,
			&i.HasLevels,
			&i.LevelScaling,
			&i.LevelRule,
			&i.Tiers,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTemplates = `-- name: ListPublicTemplates :many
SELECT id, name, description, creator_user_id, stats, rules, components, is_private, created_at, updated_at
FROM templates
WHERE is_private = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicTemplatesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublicTemplates(ctx context.Context, arg ListPublicTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listPublicTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.Stats,
			&i.Rules,
			&i.Components,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByUser = `-- name: ListTemplatesByUser :many
SELECT id, name, description, creator_user_id, stats, rules, components, is_private, created_at, updated_at
FROM templates
WHERE creator_user_id = $1 AND is_private = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTemplatesByUserParams struct {
	CreatorUserID int32
	Limit         int32
	Offset        int32
}

func (q *Queries) ListTemplatesByUser(ctx context.Context, arg ListTemplatesByUserParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByUser, arg.CreatorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.Stats,
			&i.Rules,
			&i.Components,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at = $3,
    tags = COALESCE($4, tags),
    components = COALESCE($5, components),
    is_private = COALESCE($6, is_private)
WHERE id = $7
RETURNING id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
`

type UpdateBuildParams struct {
	Name        string
	Description pgtype.Text
	UpdatedAt   pgtype.Timestamptz
	Tags        []string
	Components  []byte
	IsPrivate   bool
	ID          string
}

type UpdateBuildRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (UpdateBuildRow, error) {
	row := q.db.QueryRow(ctx, updateBuild,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.Tags,
		arg.Components,
		arg.IsPrivate,
		arg.ID,
	)
	var i UpdateBuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const updateBuildVoteScore = `-- name: UpdateBuildVoteScore :one
UPDATE builds
SET
    vote_score = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
`

type UpdateBuildVoteScoreParams struct {
	VoteScore int32
	UpdatedAt pgtype.Timestamptz
	ID        string
}

type UpdateBuildVoteScoreRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) UpdateBuildVoteScore(ctx context.Context, arg UpdateBuildVoteScoreParams) (UpdateBuildVoteScoreRow, error) {
	row := q.db.QueryRow(ctx, updateBuildVoteScore, arg.VoteScore, arg.UpdatedAt, arg.ID)
	var i UpdateBuildVoteScoreRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    category = COALESCE($3, category),
    effects = COALESCE($4, effects),
    has_levels = COALESCE($5, has_levels),
    level_scaling = COALESCE($6, level_scaling),
    level_rule = COALESCE($7, level_rule),
    tiers = COALESCE($8, tiers),
    is_deleted = COALESCE($9, is_deleted),
    updated_at = $10
WHERE id = $11 AND template_id = $12
RETURNING id, template_id, scoped_number, name, description, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
`

type UpdateComponentParams struct {
	Name         string
	Description  pgtype.Text
	Category     string
	Effects      []byte
	HasLevels    bool
	LevelScaling pgtype.Text
	LevelRule    []byte
	Tiers        []byte
	IsDeleted    bool
	UpdatedAt    pgtype.Timestamptz
	ID           int64
	TemplateID   string
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Effects,
		arg.HasLevels,
		arg.LevelScaling,
		arg.LevelRule,
		arg.Tiers,
		arg.IsDeleted,
		arg.UpdatedAt,
		arg.ID,
		arg.TemplateID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET
    name = $1,
    rules = $2,
    updated_at = $3
WHERE id = $4
RETURNING id, name, description, creator_user_id, stats, rules, components, is_private, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name      string
	Rules     []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Rules,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.Components,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($1, username),
    email = COALESCE($2, email),
    password = COALESCE($3, password),
    updated_at = $4
WHERE id = $5
RETURNING id, username, email, password, created_at, updated_at
`

type UpdateUserParams struct {
	Username  string
	Email     string
	Password  string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, created_at, updated_at
`

type UpdateUserEmailParams struct {
	Email     string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	Password  string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.Password, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users
SET username = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, created_at, updated_at
`

type UpdateUserUsernameParams struct {
	Username  string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.Username, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBuildSlot = `-- name: UpsertBuildSlot :one
INSERT INTO build_slots (
    build_id,
    category,
    position,
    component_id,
    level,
    tier
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (build_id, category, position)
DO UPDATE SET
    component_id = EXCLUDED.component_id,
    level = EXCLUDED.level,
    tier = EXCLUDED.tier
RETURNING build_id, category, position, component_id, level, tier
`

type UpsertBuildSlotParams struct {
	BuildID     string
	Category    string
	Position    int32
	ComponentID pgtype.Int8
	Level       pgtype.Int4
	Tier        pgtype.Int4
}

func (q *Queries) UpsertBuildSlot(ctx context.Context, arg UpsertBuildSlotParams) (BuildSlot, error) {
	row := q.db.QueryRow(ctx, upsertBuildSlot,
		arg.BuildID,
		arg.Category,
		arg.Position,
		arg.ComponentID,
		arg.Level,
		arg.Tier,
	)
	var i BuildSlot
	err := row.Scan(
		&i.BuildID,
		&i.Category,
		&i.Position,
		&i.ComponentID,
		&i.Level,
		&i.Tier,
	)
	return i, err
}

const upsertBuildVote = `-- name: UpsertBuildVote :one
INSERT INTO build_votes (
    user_id,
    build_id,
    value,
    created_at
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id, build_id)
DO UPDATE SET
    value = EXCLUDED.value,
    created_at = EXCLUDED.created_at
RETURNING user_id, build_id, value, created_at
`

type UpsertBuildVoteParams struct {
	UserID    int32
	BuildID   string
	Value     int16
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertBuildVote(ctx context.Context, arg UpsertBuildVoteParams) (BuildVote, error) {
	row := q.db.QueryRow(ctx, upsertBuildVote,
		arg.UserID,
		arg.BuildID,
		arg.Value,
		arg.CreatedAt,
	)
	var i BuildVote
	err := row.Scan(
		&i.UserID,
		&i.BuildID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE email = $1 OR username = $2
)
`

type UserExistsParams struct {
	Email    string
	Username string
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
