// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptSuggestion = `-- name: AcceptSuggestion :one
UPDATE template_suggestions
SET
    status = 'accepted',
    author_notified = FALSE,
    updated_at = $3
WHERE id = $1 AND template_id = $2
RETURNING id, template_id, author_user_id, description, components, status, author_notified, created_at, updated_at
`

type AcceptSuggestionParams struct {
	ID         string
	TemplateID string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) AcceptSuggestion(ctx context.Context, arg AcceptSuggestionParams) (TemplateSuggestion, error) {
	row := q.db.QueryRow(ctx, acceptSuggestion, arg.ID, arg.TemplateID, arg.UpdatedAt)
	var i TemplateSuggestion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AuthorUserID,
		&i.Description,
		&i.Components,
		&i.Status,
		&i.AuthorNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAcceptedSuggestionsForAuthorUnnotified = `-- name: CountAcceptedSuggestionsForAuthorUnnotified :one
SELECT COUNT(*)
FROM template_suggestions
WHERE author_user_id = $1 AND status = 'accepted' AND author_notified = FALSE
`

func (q *Queries) CountAcceptedSuggestionsForAuthorUnnotified(ctx context.Context, authorUserID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAcceptedSuggestionsForAuthorUnnotified, authorUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBuildsByUser = `-- name: CountBuildsByUser :one
SELECT COUNT(*)
FROM builds
WHERE creator_user_id = $1
`

func (q *Queries) CountBuildsByUser(ctx context.Context, creatorUserID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildsByUser, creatorUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikedBuildsByUser = `-- name: CountLikedBuildsByUser :one
SELECT COUNT(*)
FROM build_votes v
JOIN builds b ON b.id = v.build_id
WHERE v.user_id = $1 AND v.value = 1 AND (b.is_private = FALSE OR b.creator_user_id = $1)
`

func (q *Queries) CountLikedBuildsByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countLikedBuildsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingSuggestionsForOwner = `-- name: CountPendingSuggestionsForOwner :one
SELECT COUNT(*)
FROM template_suggestions s
JOIN templates t ON t.id = s.template_id
WHERE t.creator_user_id = $1 AND s.status = 'pending'
`

func (q *Queries) CountPendingSuggestionsForOwner(ctx context.Context, creatorUserID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSuggestionsForOwner, creatorUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicBuildVotes = `-- name: CountPublicBuildVotes :one
SELECT COUNT(*)
FROM build_votes v
JOIN builds b ON b.id = v.build_id
WHERE v.value = 1 AND b.is_private = FALSE
`

func (q *Queries) CountPublicBuildVotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicBuildVotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicBuilds = `-- name: CountPublicBuilds :one
SELECT COUNT(*)
FROM builds
WHERE is_private = FALSE
`

func (q *Queries) CountPublicBuilds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicBuilds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicTemplates = `-- name: CountPublicTemplates :one
SELECT COUNT(*)
FROM templates
WHERE is_private = FALSE
`

func (q *Queries) CountPublicTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplatesByUser = `-- name: CountTemplatesByUser :one
SELECT COUNT(*)
FROM templates
WHERE creator_user_id = $1 AND (is_private = FALSE OR $2::integer = creator_user_id)
`

type CountTemplatesByUserParams struct {
	CreatorUserID int32
	RequesterID   int32
}

func (q *Queries) CountTemplatesByUser(ctx context.Context, arg CountTemplatesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplatesByUser, arg.CreatorUserID, arg.RequesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    id,
    name,
    description,
    creator_user_id,
    template_id,
    created_at,
    updated_at,
    tags,
    vote_score,
    components,
    is_private
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
`

type CreateBuildParams struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

type CreateBuildRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (CreateBuildRow, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatorUserID,
		arg.TemplateID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Tags,
		arg.VoteScore,
		arg.Components,
		arg.IsPrivate,
	)
	var i CreateBuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (
    template_id,
    scoped_number,
    name,
    description,
    sub_category,
    category,
    effects,
    has_levels,
    level_scaling,
    level_rule,
    tiers,
    is_deleted,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, template_id, scoped_number, name, description, sub_category, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
`

type CreateComponentParams struct {
	TemplateID   string
	ScopedNumber int32
	Name         string
	Description  pgtype.Text
	SubCategory  pgtype.Text
	Category     string
	Effects      []byte
	HasLevels    bool
	LevelScaling pgtype.Text
	LevelRule    []byte
	Tiers        []byte
	IsDeleted    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.TemplateID,
		arg.ScopedNumber,
		arg.Name,
		arg.Description,
		arg.SubCategory,
		arg.Category,
		arg.Effects,
		arg.HasLevels,
		arg.LevelScaling,
		arg.LevelRule,
		arg.Tiers,
		arg.IsDeleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.SubCategory,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSuggestion = `-- name: CreateSuggestion :one
INSERT INTO template_suggestions (
    id,
    template_id,
    author_user_id,
    description,
    components,
    status,
    author_notified,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, template_id, author_user_id, description, components, status, author_notified, created_at, updated_at
`

type CreateSuggestionParams struct {
	ID             string
	TemplateID     string
	AuthorUserID   int32
	Description    pgtype.Text
	Components     []byte
	Status         string
	AuthorNotified bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateSuggestion(ctx context.Context, arg CreateSuggestionParams) (TemplateSuggestion, error) {
	row := q.db.QueryRow(ctx, createSuggestion,
		arg.ID,
		arg.TemplateID,
		arg.AuthorUserID,
		arg.Description,
		arg.Components,
		arg.Status,
		arg.AuthorNotified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TemplateSuggestion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AuthorUserID,
		&i.Description,
		&i.Components,
		&i.Status,
		&i.AuthorNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    id,
    name,
    description,
    creator_user_id,
    stats,
    rules,
    is_private,
    allow_suggestions,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, description, creator_user_id, stats, rules, is_private, allow_suggestions, created_at, updated_at
`

type CreateTemplateParams struct {
	ID               string
	Name             string
	Description      pgtype.Text
	CreatorUserID    int32
	Stats            []byte
	Rules            []byte
	IsPrivate        bool
	AllowSuggestions bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatorUserID,
		arg.Stats,
		arg.Rules,
		arg.IsPrivate,
		arg.AllowSuggestions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.IsPrivate,
		&i.AllowSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password,
    google_sub,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, username, email, password, google_sub, created_at, updated_at
`

type CreateUserParams struct {
	Username  string
	Email     string
	Password  string
	GoogleSub pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.GoogleSub,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBuild = `-- name: DeleteBuild :exec
DELETE FROM builds
WHERE id = $1
`

func (q *Queries) DeleteBuild(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBuild, id)
	return err
}

const deleteBuildSlotsByBuild = `-- name: DeleteBuildSlotsByBuild :exec
DELETE FROM build_slots
WHERE build_id = $1
`

func (q *Queries) DeleteBuildSlotsByBuild(ctx context.Context, buildID string) error {
	_, err := q.db.Exec(ctx, deleteBuildSlotsByBuild, buildID)
	return err
}

const deleteBuildVote = `-- name: DeleteBuildVote :exec
DELETE FROM build_votes
WHERE user_id = $1 AND build_id = $2
`

type DeleteBuildVoteParams struct {
	UserID  int32
	BuildID string
}

func (q *Queries) DeleteBuildVote(ctx context.Context, arg DeleteBuildVoteParams) error {
	_, err := q.db.Exec(ctx, deleteBuildVote, arg.UserID, arg.BuildID)
	return err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components
WHERE id = $1 AND template_id = $2
`

type DeleteComponentParams struct {
	ID         int64
	TemplateID string
}

func (q *Queries) DeleteComponent(ctx context.Context, arg DeleteComponentParams) error {
	_, err := q.db.Exec(ctx, deleteComponent, arg.ID, arg.TemplateID)
	return err
}

const deleteComponentsByScopedNumberList = `-- name: DeleteComponentsByScopedNumberList :exec
DELETE FROM components
WHERE template_id = $1 AND scoped_number = ANY($2::int[])
`

type DeleteComponentsByScopedNumberListParams struct {
	TemplateID    string
	ScopedNumbers []int32
}

func (q *Queries) DeleteComponentsByScopedNumberList(ctx context.Context, arg DeleteComponentsByScopedNumberListParams) error {
	_, err := q.db.Exec(ctx, deleteComponentsByScopedNumberList, arg.TemplateID, arg.ScopedNumbers)
	return err
}

const deleteComponentsByScopedNumbers = `-- name: DeleteComponentsByScopedNumbers :exec
DELETE FROM components
WHERE template_id = $1 AND NOT (scoped_number = ANY($2::int[]))
`

type DeleteComponentsByScopedNumbersParams struct {
	TemplateID    string
	ScopedNumbers []int32
}

func (q *Queries) DeleteComponentsByScopedNumbers(ctx context.Context, arg DeleteComponentsByScopedNumbersParams) error {
	_, err := q.db.Exec(ctx, deleteComponentsByScopedNumbers, arg.TemplateID, arg.ScopedNumbers)
	return err
}

const deleteSuggestion = `-- name: DeleteSuggestion :exec
DELETE FROM template_suggestions
WHERE id = $1
`

func (q *Queries) DeleteSuggestion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSuggestion, id)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates
WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserByEmail, email)
	return err
}

const getBuildByID = `-- name: GetBuildByID :one
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE id = $1 AND is_private = FALSE
LIMIT 1
`

type GetBuildByIDRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) GetBuildByID(ctx context.Context, id string) (GetBuildByIDRow, error) {
	row := q.db.QueryRow(ctx, getBuildByID, id)
	var i GetBuildByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const getBuildByIDAny = `-- name: GetBuildByIDAny :one
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE id = $1
LIMIT 1
`

type GetBuildByIDAnyRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) GetBuildByIDAny(ctx context.Context, id string) (GetBuildByIDAnyRow, error) {
	row := q.db.QueryRow(ctx, getBuildByIDAny, id)
	var i GetBuildByIDAnyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const getBuildVote = `-- name: GetBuildVote :one
SELECT user_id, build_id, value, created_at
FROM build_votes
WHERE user_id = $1 AND build_id = $2
LIMIT 1
`

type GetBuildVoteParams struct {
	UserID  int32
	BuildID string
}

func (q *Queries) GetBuildVote(ctx context.Context, arg GetBuildVoteParams) (BuildVote, error) {
	row := q.db.QueryRow(ctx, getBuildVote, arg.UserID, arg.BuildID)
	var i BuildVote
	err := row.Scan(
		&i.UserID,
		&i.BuildID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, template_id, scoped_number, name, description, sub_category, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
FROM components
WHERE id = $1 AND template_id = $2
LIMIT 1
`

type GetComponentByIDParams struct {
	ID         int64
	TemplateID string
}

func (q *Queries) GetComponentByID(ctx context.Context, arg GetComponentByIDParams) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByID, arg.ID, arg.TemplateID)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.SubCategory,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSuggestionByTemplateAndAuthor = `-- name: GetPendingSuggestionByTemplateAndAuthor :one
SELECT id, template_id, author_user_id, description, components, status, author_notified, created_at, updated_at
FROM template_suggestions
WHERE template_id = $1 AND author_user_id = $2 AND status = 'pending'
LIMIT 1
`

type GetPendingSuggestionByTemplateAndAuthorParams struct {
	TemplateID   string
	AuthorUserID int32
}

func (q *Queries) GetPendingSuggestionByTemplateAndAuthor(ctx context.Context, arg GetPendingSuggestionByTemplateAndAuthorParams) (TemplateSuggestion, error) {
	row := q.db.QueryRow(ctx, getPendingSuggestionByTemplateAndAuthor, arg.TemplateID, arg.AuthorUserID)
	var i TemplateSuggestion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AuthorUserID,
		&i.Description,
		&i.Components,
		&i.Status,
		&i.AuthorNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuggestionByID = `-- name: GetSuggestionByID :one
SELECT id, template_id, author_user_id, description, components, status, author_notified, created_at, updated_at
FROM template_suggestions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSuggestionByID(ctx context.Context, id string) (TemplateSuggestion, error) {
	row := q.db.QueryRow(ctx, getSuggestionByID, id)
	var i TemplateSuggestion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AuthorUserID,
		&i.Description,
		&i.Components,
		&i.Status,
		&i.AuthorNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, description, creator_user_id, stats, rules, is_private, allow_suggestions, created_at, updated_at
FROM templates
WHERE id = $1 AND is_private = FALSE
LIMIT 1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.IsPrivate,
		&i.AllowSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByIDAny = `-- name: GetTemplateByIDAny :one
SELECT id, name, description, creator_user_id, stats, rules, is_private, allow_suggestions, created_at, updated_at
FROM templates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTemplateByIDAny(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByIDAny, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.IsPrivate,
		&i.AllowSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateCreatorByID = `-- name: GetTemplateCreatorByID :one
SELECT creator_user_id
FROM templates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTemplateCreatorByID(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, getTemplateCreatorByID, id)
	var creator_user_id int32
	err := row.Scan(&creator_user_id)
	return creator_user_id, err
}

const getTemplatesByIDs = `-- name: GetTemplatesByIDs :many
SELECT id, name
FROM templates
WHERE id = ANY($1::text[])
`

type GetTemplatesByIDsRow struct {
	ID   string
	Name string
}

func (q *Queries) GetTemplatesByIDs(ctx context.Context, dollar_1 []string) ([]GetTemplatesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getTemplatesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTemplatesByIDsRow
	for rows.Next() {
		var i GetTemplatesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, google_sub, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, username, email, password, google_sub, created_at, updated_at
FROM users
WHERE google_sub = $1
LIMIT 1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, google_sub, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, google_sub, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, email, google_sub, created_at, updated_at
FROM users
WHERE id = ANY($1::int[])
ORDER BY created_at DESC
`

type GetUsersByIDsRow struct {
	ID        int32
	Username  string
	Email     string
	GoogleSub pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []int32) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.GoogleSub,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUserGoogleSub = `-- name: LinkUserGoogleSub :one
UPDATE users
SET google_sub = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, google_sub, created_at, updated_at
`

type LinkUserGoogleSubParams struct {
	GoogleSub pgtype.Text
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) LinkUserGoogleSub(ctx context.Context, arg LinkUserGoogleSubParams) (User, error) {
	row := q.db.QueryRow(ctx, linkUserGoogleSub, arg.GoogleSub, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcceptedSuggestionsForAuthorUnnotified = `-- name: ListAcceptedSuggestionsForAuthorUnnotified :many
SELECT s.id, s.template_id, t.name
FROM template_suggestions s
JOIN templates t ON t.id = s.template_id
WHERE s.author_user_id = $1 AND s.status = 'accepted' AND s.author_notified = FALSE
ORDER BY s.updated_at DESC
`

type ListAcceptedSuggestionsForAuthorUnnotifiedRow struct {
	ID         string
	TemplateID string
	Name       string
}

func (q *Queries) ListAcceptedSuggestionsForAuthorUnnotified(ctx context.Context, authorUserID int32) ([]ListAcceptedSuggestionsForAuthorUnnotifiedRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedSuggestionsForAuthorUnnotified, authorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedSuggestionsForAuthorUnnotifiedRow
	for rows.Next() {
		var i ListAcceptedSuggestionsForAuthorUnnotifiedRow
		if err := rows.Scan(&i.ID, &i.TemplateID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildSlotsByBuild = `-- name: ListBuildSlotsByBuild :many
SELECT build_id, category, position, component_id, level, tier
FROM build_slots
WHERE build_id = $1
ORDER BY category, position
`

func (q *Queries) ListBuildSlotsByBuild(ctx context.Context, buildID string) ([]BuildSlot, error) {
	rows, err := q.db.Query(ctx, listBuildSlotsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildSlot
	for rows.Next() {
		var i BuildSlot
		if err := rows.Scan(
			&i.BuildID,
			&i.Category,
			&i.Position,
			&i.ComponentID,
			&i.Level,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsByTemplate = `-- name: ListBuildsByTemplate :many
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE template_id = $1 AND (is_private = FALSE OR creator_user_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListBuildsByTemplateParams struct {
	TemplateID  string
	RequesterID int32
	Offset      int32
	Limit       int32
}

type ListBuildsByTemplateRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListBuildsByTemplate(ctx context.Context, arg ListBuildsByTemplateParams) ([]ListBuildsByTemplateRow, error) {
	rows, err := q.db.Query(ctx, listBuildsByTemplate,
		arg.TemplateID,
		arg.RequesterID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildsByTemplateRow
	for rows.Next() {
		var i ListBuildsByTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsByUser = `-- name: ListBuildsByUser :many
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE creator_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBuildsByUserParams struct {
	CreatorUserID int32
	Limit         int32
	Offset        int32
}

type ListBuildsByUserRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListBuildsByUser(ctx context.Context, arg ListBuildsByUserParams) ([]ListBuildsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBuildsByUser, arg.CreatorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildsByUserRow
	for rows.Next() {
		var i ListBuildsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByTemplate = `-- name: ListComponentsByTemplate :many
SELECT id, template_id, scoped_number, name, description, sub_category, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
FROM components
WHERE template_id = $1
ORDER BY scoped_number ASC
LIMIT $2 OFFSET $3
`

type ListComponentsByTemplateParams struct {
	TemplateID string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListComponentsByTemplate(ctx context.Context, arg ListComponentsByTemplateParams) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponentsByTemplate, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ScopedNumber,
			&i.Name,
			&i.Description,
			&i.SubCategory,
			&i.Category,
			&i.Effects,
			&i.HasLevels,
			&i.LevelScaling,
			&i.LevelRule,
			&i.Tiers,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedBuildsByUser = `-- name: ListLikedBuildsByUser :many
SELECT b.id, b.name, b.description, b.creator_user_id, b.template_id, b.created_at, b.updated_at, b.tags, b.vote_score, b.components, b.is_private
FROM build_votes v
JOIN builds b ON b.id = v.build_id
WHERE v.user_id = $1 AND v.value = 1 AND (b.is_private = FALSE OR b.creator_user_id = $1)
ORDER BY v.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLikedBuildsByUserParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

type ListLikedBuildsByUserRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListLikedBuildsByUser(ctx context.Context, arg ListLikedBuildsByUserParams) ([]ListLikedBuildsByUserRow, error) {
	rows, err := q.db.Query(ctx, listLikedBuildsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLikedBuildsByUserRow
	for rows.Next() {
		var i ListLikedBuildsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSuggestionCountsForOwner = `-- name: ListPendingSuggestionCountsForOwner :many
SELECT t.id AS template_id, t.name AS template_name, COUNT(s.id) AS pending_count
FROM templates t
LEFT JOIN template_suggestions s ON s.template_id = t.id AND s.status = 'pending'
WHERE t.creator_user_id = $1
GROUP BY t.id, t.name
HAVING COUNT(s.id) > 0
ORDER BY t.name ASC
`

type ListPendingSuggestionCountsForOwnerRow struct {
	TemplateID   string
	TemplateName string
	PendingCount int64
}

func (q *Queries) ListPendingSuggestionCountsForOwner(ctx context.Context, creatorUserID int32) ([]ListPendingSuggestionCountsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listPendingSuggestionCountsForOwner, creatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSuggestionCountsForOwnerRow
	for rows.Next() {
		var i ListPendingSuggestionCountsForOwnerRow
		if err := rows.Scan(&i.TemplateID, &i.TemplateName, &i.PendingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBuilds = `-- name: ListPublicBuilds :many
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE is_private = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListPublicBuildsParams struct {
	Offset int32
	Limit  int32
}

type ListPublicBuildsRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListPublicBuilds(ctx context.Context, arg ListPublicBuildsParams) ([]ListPublicBuildsRow, error) {
	rows, err := q.db.Query(ctx, listPublicBuilds, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicBuildsRow
	for rows.Next() {
		var i ListPublicBuildsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBuildsByTemplate = `-- name: ListPublicBuildsByTemplate :many
SELECT id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
FROM builds
WHERE is_private = FALSE AND template_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListPublicBuildsByTemplateParams struct {
	TemplateID string
	Offset     int32
	Limit      int32
}

type ListPublicBuildsByTemplateRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) ListPublicBuildsByTemplate(ctx context.Context, arg ListPublicBuildsByTemplateParams) ([]ListPublicBuildsByTemplateRow, error) {
	rows, err := q.db.Query(ctx, listPublicBuildsByTemplate, arg.TemplateID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicBuildsByTemplateRow
	for rows.Next() {
		var i ListPublicBuildsByTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.VoteScore,
			&i.Components,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTemplates = `-- name: ListPublicTemplates :many
SELECT id, name, description, creator_user_id, stats, rules, is_private, allow_suggestions, created_at, updated_at
FROM templates
WHERE is_private = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicTemplatesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublicTemplates(ctx context.Context, arg ListPublicTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listPublicTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.Stats,
			&i.Rules,
			&i.IsPrivate,
			&i.AllowSuggestions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestionsByTemplate = `-- name: ListSuggestionsByTemplate :many
SELECT id, template_id, author_user_id, description, components, status, author_notified, created_at, updated_at
FROM template_suggestions
WHERE template_id = $1 AND status = 'pending'
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListSuggestionsByTemplateParams struct {
	TemplateID string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListSuggestionsByTemplate(ctx context.Context, arg ListSuggestionsByTemplateParams) ([]TemplateSuggestion, error) {
	rows, err := q.db.Query(ctx, listSuggestionsByTemplate, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateSuggestion
	for rows.Next() {
		var i TemplateSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AuthorUserID,
			&i.Description,
			&i.Components,
			&i.Status,
			&i.AuthorNotified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByUser = `-- name: ListTemplatesByUser :many
SELECT id, name, description, creator_user_id, stats, rules, is_private, allow_suggestions, created_at, updated_at
FROM templates
WHERE creator_user_id = $1 AND (is_private = FALSE OR $2::integer = creator_user_id)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTemplatesByUserParams struct {
	CreatorUserID int32
	RequesterID   int32
	Offset        int32
	Limit         int32
}

func (q *Queries) ListTemplatesByUser(ctx context.Context, arg ListTemplatesByUserParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByUser,
		arg.CreatorUserID,
		arg.RequesterID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorUserID,
			&i.Stats,
			&i.Rules,
			&i.IsPrivate,
			&i.AllowSuggestions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, google_sub, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID        int32
	Username  string
	Email     string
	GoogleSub pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.GoogleSub,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSuggestionAuthorNotified = `-- name: MarkSuggestionAuthorNotified :exec
UPDATE template_suggestions
SET author_notified = TRUE
WHERE id = ANY($1::text[])
`

func (q *Queries) MarkSuggestionAuthorNotified(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, markSuggestionAuthorNotified, dollar_1)
	return err
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at = $3,
    tags = COALESCE($4, tags),
    components = COALESCE($5, components),
    is_private = COALESCE($6, is_private)
WHERE id = $7
RETURNING id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
`

type UpdateBuildParams struct {
	Name        string
	Description pgtype.Text
	UpdatedAt   pgtype.Timestamptz
	Tags        []string
	Components  []byte
	IsPrivate   bool
	ID          string
}

type UpdateBuildRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (UpdateBuildRow, error) {
	row := q.db.QueryRow(ctx, updateBuild,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.Tags,
		arg.Components,
		arg.IsPrivate,
		arg.ID,
	)
	var i UpdateBuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const updateBuildVoteScore = `-- name: UpdateBuildVoteScore :one
UPDATE builds
SET
    vote_score = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, name, description, creator_user_id, template_id, created_at, updated_at, tags, vote_score, components, is_private
`

type UpdateBuildVoteScoreParams struct {
	VoteScore int32
	UpdatedAt pgtype.Timestamptz
	ID        string
}

type UpdateBuildVoteScoreRow struct {
	ID            string
	Name          string
	Description   pgtype.Text
	CreatorUserID int32
	TemplateID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
	VoteScore     int32
	Components    []byte
	IsPrivate     bool
}

func (q *Queries) UpdateBuildVoteScore(ctx context.Context, arg UpdateBuildVoteScoreParams) (UpdateBuildVoteScoreRow, error) {
	row := q.db.QueryRow(ctx, updateBuildVoteScore, arg.VoteScore, arg.UpdatedAt, arg.ID)
	var i UpdateBuildVoteScoreRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.VoteScore,
		&i.Components,
		&i.IsPrivate,
	)
	return i, err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    sub_category = COALESCE($3, sub_category),
    category = COALESCE($4, category),
    effects = COALESCE($5, effects),
    has_levels = COALESCE($6, has_levels),
    level_scaling = COALESCE($7, level_scaling),
    level_rule = COALESCE($8, level_rule),
    tiers = COALESCE($9, tiers),
    is_deleted = COALESCE($10, is_deleted),
    updated_at = $11
WHERE id = $12 AND template_id = $13
RETURNING id, template_id, scoped_number, name, description, sub_category, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
`

type UpdateComponentParams struct {
	Name         string
	Description  pgtype.Text
	SubCategory  pgtype.Text
	Category     string
	Effects      []byte
	HasLevels    bool
	LevelScaling pgtype.Text
	LevelRule    []byte
	Tiers        []byte
	IsDeleted    bool
	UpdatedAt    pgtype.Timestamptz
	ID           int64
	TemplateID   string
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.Name,
		arg.Description,
		arg.SubCategory,
		arg.Category,
		arg.Effects,
		arg.HasLevels,
		arg.LevelScaling,
		arg.LevelRule,
		arg.Tiers,
		arg.IsDeleted,
		arg.UpdatedAt,
		arg.ID,
		arg.TemplateID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.SubCategory,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSuggestion = `-- name: UpdateSuggestion :one
UPDATE template_suggestions
SET
    description = $1,
    components = $2,
    updated_at = $3
WHERE id = $4
RETURNING id, template_id, author_user_id, description, components, status, author_notified, created_at, updated_at
`

type UpdateSuggestionParams struct {
	Description pgtype.Text
	Components  []byte
	UpdatedAt   pgtype.Timestamptz
	ID          string
}

func (q *Queries) UpdateSuggestion(ctx context.Context, arg UpdateSuggestionParams) (TemplateSuggestion, error) {
	row := q.db.QueryRow(ctx, updateSuggestion,
		arg.Description,
		arg.Components,
		arg.UpdatedAt,
		arg.ID,
	)
	var i TemplateSuggestion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AuthorUserID,
		&i.Description,
		&i.Components,
		&i.Status,
		&i.AuthorNotified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET
    name = $1,
    description = COALESCE($2, description),
    stats = COALESCE($3, stats),
    rules = $4,
    is_private = $5,
    allow_suggestions = $6,
    updated_at = $7
WHERE id = $8
RETURNING id, name, description, creator_user_id, stats, rules, is_private, allow_suggestions, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name             string
	Description      pgtype.Text
	Stats            []byte
	Rules            []byte
	IsPrivate        bool
	AllowSuggestions bool
	UpdatedAt        pgtype.Timestamptz
	ID               string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Description,
		arg.Stats,
		arg.Rules,
		arg.IsPrivate,
		arg.AllowSuggestions,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.Stats,
		&i.Rules,
		&i.IsPrivate,
		&i.AllowSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($1, username),
    email = COALESCE($2, email),
    password = COALESCE($3, password),
    google_sub = COALESCE($4, google_sub),
    updated_at = $5
WHERE id = $6
RETURNING id, username, email, password, google_sub, created_at, updated_at
`

type UpdateUserParams struct {
	Username  string
	Email     string
	Password  string
	GoogleSub pgtype.Text
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.GoogleSub,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, google_sub, created_at, updated_at
`

type UpdateUserEmailParams struct {
	Email     string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, google_sub, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	Password  string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.Password, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users
SET username = $1, updated_at = $2
WHERE id = $3
RETURNING id, username, email, password, google_sub, created_at, updated_at
`

type UpdateUserUsernameParams struct {
	Username  string
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.Username, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBuildSlot = `-- name: UpsertBuildSlot :one
INSERT INTO build_slots (
    build_id,
    category,
    position,
    component_id,
    level,
    tier
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (build_id, category, position)
DO UPDATE SET
    component_id = EXCLUDED.component_id,
    level = EXCLUDED.level,
    tier = EXCLUDED.tier
RETURNING build_id, category, position, component_id, level, tier
`

type UpsertBuildSlotParams struct {
	BuildID     string
	Category    string
	Position    int32
	ComponentID pgtype.Int8
	Level       pgtype.Int4
	Tier        pgtype.Int4
}

func (q *Queries) UpsertBuildSlot(ctx context.Context, arg UpsertBuildSlotParams) (BuildSlot, error) {
	row := q.db.QueryRow(ctx, upsertBuildSlot,
		arg.BuildID,
		arg.Category,
		arg.Position,
		arg.ComponentID,
		arg.Level,
		arg.Tier,
	)
	var i BuildSlot
	err := row.Scan(
		&i.BuildID,
		&i.Category,
		&i.Position,
		&i.ComponentID,
		&i.Level,
		&i.Tier,
	)
	return i, err
}

const upsertBuildVote = `-- name: UpsertBuildVote :one
INSERT INTO build_votes (
    user_id,
    build_id,
    value,
    created_at
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id, build_id)
DO UPDATE SET
    value = EXCLUDED.value,
    created_at = EXCLUDED.created_at
RETURNING user_id, build_id, value, created_at
`

type UpsertBuildVoteParams struct {
	UserID    int32
	BuildID   string
	Value     int16
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertBuildVote(ctx context.Context, arg UpsertBuildVoteParams) (BuildVote, error) {
	row := q.db.QueryRow(ctx, upsertBuildVote,
		arg.UserID,
		arg.BuildID,
		arg.Value,
		arg.CreatedAt,
	)
	var i BuildVote
	err := row.Scan(
		&i.UserID,
		&i.BuildID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const upsertComponent = `-- name: UpsertComponent :one
INSERT INTO components (
    template_id,
    scoped_number,
    name,
    description,
    sub_category,
    category,
    effects,
    has_levels,
    level_scaling,
    level_rule,
    tiers,
    is_deleted,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) ON CONFLICT (template_id, scoped_number)
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    sub_category = EXCLUDED.sub_category,
    category = EXCLUDED.category,
    effects = EXCLUDED.effects,
    has_levels = EXCLUDED.has_levels,
    level_scaling = EXCLUDED.level_scaling,
    level_rule = EXCLUDED.level_rule,
    tiers = EXCLUDED.tiers,
    is_deleted = EXCLUDED.is_deleted,
    updated_at = EXCLUDED.updated_at
RETURNING id, template_id, scoped_number, name, description, sub_category, category, effects, has_levels, level_scaling, level_rule, tiers, is_deleted, created_at, updated_at
`

type UpsertComponentParams struct {
	TemplateID   string
	ScopedNumber int32
	Name         string
	Description  pgtype.Text
	SubCategory  pgtype.Text
	Category     string
	Effects      []byte
	HasLevels    bool
	LevelScaling pgtype.Text
	LevelRule    []byte
	Tiers        []byte
	IsDeleted    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertComponent(ctx context.Context, arg UpsertComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, upsertComponent,
		arg.TemplateID,
		arg.ScopedNumber,
		arg.Name,
		arg.Description,
		arg.SubCategory,
		arg.Category,
		arg.Effects,
		arg.HasLevels,
		arg.LevelScaling,
		arg.LevelRule,
		arg.Tiers,
		arg.IsDeleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ScopedNumber,
		&i.Name,
		&i.Description,
		&i.SubCategory,
		&i.Category,
		&i.Effects,
		&i.HasLevels,
		&i.LevelScaling,
		&i.LevelRule,
		&i.Tiers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE email = $1 OR username = $2
)
`

type UserExistsParams struct {
	Email    string
	Username string
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
